using System.Text.Json;

namespace PipeDream;

/// <summary>
/// Static sprite display table: cell-relative OAM entries (tile index, attr, size,
/// offset) per vanilla sprite number, generated ONCE from a clean ROM by
/// `--gen-spritedisplay` and embedded as SpriteDisplay.json. OAM tile indexes are
/// level-independent — pixels resolve per level through the SP GFX slots + palette
/// (SpriteRender.Draw) — so lookups replace the 65816 capture everywhere a vanilla
/// sprite is displayed. PIXI/custom sprites (extra bits >= 2) still use live capture.
/// </summary>
public static class SpriteDisplay
{
    private static Dictionary<int, SpriteRender.Oam[]>? table;

    public static bool TryGet(int number, out SpriteRender.Oam[] rel)
    {
        table ??= LoadEmbedded();
        return table.TryGetValue(number, out rel!);
    }

    private static Dictionary<int, SpriteRender.Oam[]> LoadEmbedded()
    {
        try
        {
            using var s = typeof(SpriteDisplay).Assembly.GetManifestResourceStream("SpriteDisplay.json");
            if (s is null) return new();
            using var r = new StreamReader(s);
            return Parse(r.ReadToEnd());
        }
        catch { return new(); }
    }

    public static Dictionary<int, SpriteRender.Oam[]> Parse(string json)
    {
        var result = new Dictionary<int, SpriteRender.Oam[]>();
        using var doc = JsonDocument.Parse(json);
        foreach (var p in doc.RootElement.GetProperty("sprites").EnumerateObject())
        {
            int num = Convert.ToInt32(p.Name, 16);
            var list = new List<SpriteRender.Oam>();
            foreach (var e in p.Value.EnumerateArray())
            {
                var v = e.EnumerateArray().Select(x => x.GetInt32()).ToArray();
                list.Add(new SpriteRender.Oam(v[0], v[1], v[2], v[3], v[4] != 0));
            }
            result[num] = list.ToArray();
        }
        return result;
    }

    /// <summary>Generate the JSON table from a ROM (canonical capture per sprite number).</summary>
    public static string Generate(Rom rom)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("{");
        sb.AppendLine("  \"_source\": \"generated by --gen-spritedisplay from a clean SMW ROM; entries are [dx, dy, tile, attr, big] cell-relative OAM (CONTRACT 14)\",");
        sb.AppendLine("  \"sprites\": {");
        var nums = Enumerable.Range(0x00, 0xC9).Concat(new[] { 0xDA, 0xDB, 0xDC, 0xDD, 0xDF });
        bool first = true;
        foreach (int n in nums)
        {
            var oam = SpriteRender.CaptureRelative(rom, n);
            if (oam is null) continue;
            if (!first) sb.AppendLine(",");
            first = false;
            var entries = string.Join(", ", oam.Select(o => $"[{o.X},{o.Y},{o.Tile},{o.Attr},{(o.Big ? 1 : 0)}]"));
            sb.Append($"    \"{n:X2}\": [{entries}]");
        }
        sb.AppendLine();
        sb.AppendLine("  }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
